#!/bin/bash


if [ -f /opt/container_watchers ]; then
    for container in $(</opt/container_watchers); do
        container_id=$(echo $container| cut -d'.' -f1)
        restart_hour=$(echo $container| cut -d'.' -f2|cut -d":" -f 1)
        restart_min=$(echo $container| cut -d'.' -f2|cut -d":" -f 2)

        echo -n "checking containerid: ${container_id}"
        echo "scheduled to restart at: ${restart_hour} hrs and ${restart_min} mins"

        if [[ $((${restart_hour}-$(date -u +%H))) -eq 0 ]]; then
            if [[ $((${restart_min}-$(date -u +%M))) -eq 0 ]]; then
                echo "restarting: ${container_id}"
                docker restart ${container_id}
            fi
        fi
    done
fi
