#!/bin/bash


if [ -f /opt/container_watchers ]; then
    for container in $(cat /opt/container_watchers| grep -v '^#'); do
        container_id=$(echo $container| cut -d'.' -f1)
        action=$(echo $container| cut -d'.' -f2)
        restart_hour=$(echo $container| cut -d'.' -f3|cut -d":" -f 1)
        restart_min=$(echo $container| cut -d'.' -f3|cut -d":" -f 2)

        echo -n "checking containerid: ${container_id}"
        echo "scheduled to restart at: ${restart_hour} hrs and ${restart_min} mins"

        if [[ $((${restart_hour}-$(date -u +%H))) -eq 0 ]]; then
            if [[ $((${restart_min}-$(date -u +%M))) -eq 0 ]]; then
                echo "${action}: ${container_id}"
                docker ${action} ${container_id}
            fi
        fi
    done
fi
